const cafes = [
	{
		id: 1,
		name: "Кофейня 'Аромат'",
		description: "Уютное место с ароматным кофе и свежей выпечкой",
		address: "ул. Арбат, д. 15",
		subway: "Arbat",
		workingHours: "8:00 - 20:00",
		image: "",
	},
	{
		id: 2,
		name: "Кафе 'У фонтана'",
		description: "Кафе с видом на фонтан в Александровском саду",
		address: "Александровский сад, вход 2",
		subway: "Alexanders Garden",
		workingHours: "9:00 - 22:00",
		image: "",
	},
	{
		id: 3,
		name: "Бистро 'Московское'",
		description: "Традиционная русская кухня в центре Москвы",
		address: "Московская пл., д. 3",
		subway: "Moscow",
		workingHours: "10:00 - 23:00",
		image: "https://example.com/moscow.jpg",
	},
	{
		id: 4,
		name: "Кафе 'Парковое'",
		description: "Летняя веранда в парке культуры",
		address: "Парк Культуры, центральная аллея",
		subway: "Culture",
		workingHours: "8:00 - 21:00",
		image: "",
	},
	{
		id: 5,
		name: "Ресторан 'Театральный'",
		description: "Элегантный ресторан для театралов",
		address: "Театральная пл., д. 1",
		subway: "Theater",
		workingHours: "11:00 - 00:00",
		image: "https://example.com/theater.jpg",
	},
	{
		id: 6,
		name: "Кофейня 'На Арбате'",
		description: "Маленькая кофейня с авторским кофе",
		address: "ул. Арбат, д. 28",
		subway: "Arbat",
		workingHours: "7:30 - 21:30",
		image: "",
	},
	{
		id: 7,
		name: "Кафе 'У пруда'",
		description: "Уютное кафе у пруда в парке",
		address: "Парк Культуры, у пруда",
		subway: "Culture",
		workingHours: "9:00 - 20:00",
		image: "",
	},
];
export default cafes;